export const users = [
    {
        id: 1,
        fullName: "Omkar Chikhale",
        username: "omkar",
        email: "omkar@gmail.com",
        password: "123",
        role : "ADMIN",
        gender: "male",
        bio : "Hello I am Omkar",
        profileImage : `https://randomuser.me/api/portraits/men/${Math.floor(Math.random()*100)}.jpg`,
        createdAt : new Date().toISOString(),
        updatedAt : new Date().toISOString(),
    },
    {
        id: 2,
        fullName: "Sakshi Chavan",
        username: "sakshi",
        email: "sakshi@gmail.com",
        password: "123",
        role : "AUTHOR",
        gender: "female",
        bio : "Hello I am Sakshi",
        profileImage : `https://randomuser.me/api/portraits/women/${Math.floor(Math.random()*100)}.jpg`,
        createdAt : new Date().toISOString(),
        updatedAt : new Date().toISOString(),
    },
    {
        id: 3,
        fullName: "Aman Pandey",
        username: "aman",
        email: "aman@gmail.com",
        password: "123",
        role : "READER",
        gender: "male",
        bio : "Hello I am Aman",
        profileImage : `https://randomuser.me/api/portraits/men/${Math.floor(Math.random()*100)}.jpg`,
        createdAt : new Date().toISOString(),
        updatedAt : new Date().toISOString(),
    }
]